version: "3.9"

services:
  create:
    restart: on-failure
    volumes:
      - ~/.ssh/authorized_keys:/root/.ssh/authorized_keys:ro
      - ~/.oci:/root/.oci:ro
    build:
      context: .
    image: get_oracle_a1
    command:
      - create
      - --verbose
      - -p
      - profile_name
      - -n
      - instance_name
      - -c
      - "2"
      - -m
      - "12"

  increase:
    restart: on-failure
    volumes:
      - ~/.ssh/authorized_keys:/root/.ssh/authorized_keys:ro
      - ~/.oci:/root/.oci:ro
    build:
      context: .
    image: get_oracle_a1
    command:
      - increase
      - --verbose
      - -p
      - profile_name
      - -n
      - instance_name
      - -c
      - "4"
      - -m
      - "18"
